### ISSUE TITLE
having an issue to compile

### ISSUE THREAD

**Issue by Arsaluddin** [Arsaluddin/java-music-app#1]
![issue-1](https://user-images.githubusercontent.com/91743738/187063265-c59d342a-b609-4421-95a5-e3f5d49e16e6.jpeg)

**Comment by madushanlahiru** [comment]
Hi Arsaluddin,

I checked you codebase. You need to initialize songs ArrayList first when you are creating a Album object.

```
public class Album {
      private  String name;
      private  String artist;
      private ArrayList<Song> Songs;

      public Album(String name,String artist){
        this.name=name;
        this.artist=artist;
        
        //add below line to your code
         Songs = new ArrayList<>();
      }
}
```
change the constructor in Album class as shown in above. you'll be fine for this error.

**Comment by Arsaluddin** [comment]
ThankYou so Much @madushanlahiru to resolve this issue 😊
